name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    
permissions:
  contents: read
  packages: write

jobs:
  build-test-and-publish:
    name: Build, Test and Publish – ${{ matrix.service.name }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        service:
          - name: identity
            src: src/Adopet.Identity
            tests: tests/Adopet.Identity.Tests
            dockerfile: src/Adopet.Identity/Dockerfile
            artifact: identity-service
    
    env: 
      DOTNET_NOLOGO: true 
      DOTNET_CLI_TELEMETRY_OPTOUT: true 
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/adopet.identity
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          
      - name: Detect changes
        id: changes
        run: |
          echo "CHANGED=false" >> $GITHUB_OUTPUT
          
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            DIFF_RANGE="origin/main...HEAD"
          else
            DIFF_RANGE="HEAD~1..HEAD"
          fi
          
          if git diff --name-only $DIFF_RANGE | grep "^${{ matrix.service.src }}/"; then
            echo "CHANGED=true" >> $GITHUB_OUTPUT
          fi

      - name: Skip unchanged service
        if: steps.changes.outputs.CHANGED != 'true'
        run: echo "No changes in ${{ matrix.service.name }} service"
          
      - name: Restore dependencies
        if: steps.changes.outputs.CHANGED == 'true'
        run: dotnet restore
        
      - name: Build
        if: steps.changes.outputs.CHANGED == 'true'
        run: dotnet build --no-restore -c Release
        
      - name: Run tests
        if: steps.changes.outputs.CHANGED == 'true'
        run: dotnet test ${{ matrix.service.tests }} --no-build -c Release --verbosity normal
        
      - name: Publish
        if: steps.changes.outputs.CHANGED == 'true'
        run: |
          dotnet publish ${{ matrix.service.src }} \
          -c Release \
          -o out/${{ matrix.service.name }}

          - name: Upload artifact
            if: steps.changes.outputs.CHANGED == 'true'
            uses: actions/upload-artifact@v4
            with:
              name: ${{ matrix.service.artifact }}
              path: out/${{ matrix.service.name }}
        
      - name: Setup Docker Buildx
        if: steps.changes.outputs.CHANGED == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR 
        if: steps.changes.outputs.CHANGED == 'true' && github.ref == 'refs/heads/main' 
        uses: docker/login-action@v3 
        with: 
          registry: ghcr.io 
          username: ${{ github.actor }} 
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Build and Push Docker Image 
        if: steps.changes.outputs.CHANGED == 'true' && github.ref == 'refs/heads/main' 
        uses: docker/build-push-action@v5 
        with: 
          context: ${{ matrix.service.src }} 
          file: ${{ matrix.service.dockerfile }} 
          push: true 
          tags: | 
              ${{ env.IMAGE_NAME }}:latest 
              ${{ env.IMAGE_NAME }}:${{ github.sha }}